#!/bin/sh

if ! [ -d "/mnt/data/settings/wireless/connman" ]; then

        mkdir -p /mnt/data/settings/wireless/connman
        rm -r /var/lib/connman
fi

rm -r /var/lib/connman
ln -s -f /mnt/data/settings/wireless/connman /var/lib/connman
