#!/bin/bash

# PolyOS setup script
# Depends on a fresh install of Ubuntu 16.04 with user "poly".
# User "poly" is important as some things are currently hard-coded.
# Once You have installed Ubuntu and logged in with user "poly" open the terminal and type:
# 
# mkdir -p ~/dev/yocto-polyos/sources/
# cd ~/dev/yocto-polyos/sources/
# git clone -b pyro https://github.com/PolyVection/meta-polyvection.git
# cd meta-polyvection
# chmod +x yocto-polyos-setup
# . yocto-polyos-setup
# 
# When everything is finished just type
#
# bitbake polyos-image
#  
# When finished you will find the sdcard image in ~/dev/yocto-polyos/build/tmp/deploy/images...
#


sudo apt-get install -y gawk wget git-core diffstat unzip texinfo gcc-multilib \
     build-essential chrpath socat cpio python python3 python3-pip python3-pexpect \
     xz-utils debianutils iputils-ping device-tree-compiler u-boot-tools curl

git clone -b pyro git://git.yoctoproject.org/poky.git ~/dev/yocto-polyos/sources/poky
git clone -b pyro https://github.com/Freescale/meta-freescale.git ~/dev/yocto-polyos/sources/meta-freescale
git clone -b pyro https://github.com/openembedded/meta-openembedded.git ~/dev/yocto-polyos/sources/meta-openembedded

cd ~/dev/yocto-polyos/
source sources/poky/oe-init-build-env build

LOCAL_CONF="/home/poly/dev/yocto-polyos/build/conf/local.conf"
BB_LAYERS="/home/poly/dev/yocto-polyos/build/conf/bblayers.conf"

cat > $LOCAL_CONF <<'EOF'
MACHINE = "voltastream0"
DISTRO = "polyos"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../..')}"
DL_DIR ?= "${BSPDIR}/downloads"
SSTATE_DIR ?= "${BSPDIR}/sstate-cache"
BB_NUMBER_THREADS = "6"
PARALLEL_MAKE = "-j 6"
EXTRA_IMAGE_FEATURES = "debug-tweaks"
EOF


cat >$BB_LAYERS <<'EOF'
# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../..')}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/poly/dev/yocto-polyos/sources/poky/meta \
  /home/poly/dev/yocto-polyos/sources/poky/meta-poky \
  /home/poly/dev/yocto-polyos/sources/poky/meta-yocto-bsp \
  "

BBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-oe "
BBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-networking "
BBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-multimedia "
BBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-filesystems "
BBLAYERS += " ${BSPDIR}/sources/meta-openembedded/meta-python "
BBLAYERS += " ${BSPDIR}/sources/meta-polyvection "
BBLAYERS += " ${BSPDIR}/sources/meta-freescale "
EOF

#bitbake polyos-image

